// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Social_tap_API;
using System;

namespace SocialtapAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20171207093556_Add")]
    partial class Add
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Social_Tap_Api.Bar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<int>("BarId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Bar");
                });

            modelBuilder.Entity("Social_Tap_Api.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BarId");

                    b.Property<string>("Comment");

                    b.Property<int>("Rate");

                    b.HasKey("Id");

                    b.HasIndex("BarId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Social_Tap_Api.Review", b =>
                {
                    b.HasOne("Social_Tap_Api.Bar", "Bar")
                        .WithMany("Reviews")
                        .HasForeignKey("BarId");
                });
#pragma warning restore 612, 618
        }
    }
}
